language: node_js
branches:
  only:
    - master

node_js:
  - 16.5.0
  
addons:
  mariadb: '10.3.35'

before_install:
  - mysql -e 'CREATE USER 'get5'@'localhost'; GRANT ALL PRIVILEGES ON *.* TO 'get5'@'localhost'; CREATE DATABASE get5test'

install:
  - export NODE_ENV=test
  - yarn install
  - cp config/test.json.template config/test.json
  - sed -i -e 's/\"get5_user"/\"get5\"/g' config/test.json
  - sed -i -e "s/\"Database 16 Byte Key.\"/\"$DBKEY\"/g" config/test.json
  - sed -i -e "s/\"API Key For Steam Calls.\"/\"$STEAMAPI\"/g" config/test.json

script:
  - yarn test
